// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package usdt

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfUsdtBpfUsdtSpec struct {
	_    structs.HostLayout
	Args [12]struct {
		_           structs.HostLayout
		ValOff      uint64
		ArgType     uint32
		RegId       uint8
		ArgSigned   bool
		ArgBitshift int8
		ArgIsFloat  bool
		Pad         [1]uint8
		_           [7]byte
	}
	UsdtCookie uint64
	ArgCnt     int16
	Pad        [6]uint8
}

// loadBpfUsdt returns the embedded CollectionSpec for bpfUsdt.
func loadBpfUsdt() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfUsdtBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfUsdt: %w", err)
	}

	return spec, err
}

// loadBpfUsdtObjects loads bpfUsdt and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfUsdtObjects
//	*bpfUsdtPrograms
//	*bpfUsdtMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfUsdtObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfUsdt()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfUsdtSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfUsdtSpecs struct {
	bpfUsdtProgramSpecs
	bpfUsdtMapSpecs
	bpfUsdtVariableSpecs
}

// bpfUsdtProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfUsdtProgramSpecs struct {
	ConstProbe     *ebpf.ProgramSpec `ebpf:"const_probe"`
	Int32Args      *ebpf.ProgramSpec `ebpf:"int32_args"`
	Int64Args      *ebpf.ProgramSpec `ebpf:"int64_args"`
	MemoryProbe    *ebpf.ProgramSpec `ebpf:"memory_probe"`
	MixedProbe     *ebpf.ProgramSpec `ebpf:"mixed_probe"`
	MixedRefs      *ebpf.ProgramSpec `ebpf:"mixed_refs"`
	SimpleProbe    *ebpf.ProgramSpec `ebpf:"simple_probe"`
	Uint8Args      *ebpf.ProgramSpec `ebpf:"uint8_args"`
	UsdtDummyProbe *ebpf.ProgramSpec `ebpf:"usdt_dummy_probe"`
	UsdtTestMulti  *ebpf.ProgramSpec `ebpf:"usdt_test_multi"`
}

// bpfUsdtMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfUsdtMapSpecs struct {
	BpfUsdtSpecs    *ebpf.MapSpec `ebpf:"__bpf_usdt_specs"`
	UsdtTestResults *ebpf.MapSpec `ebpf:"usdt_test_results"`
}

// bpfUsdtVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfUsdtVariableSpecs struct {
	WithDebugOutput *ebpf.VariableSpec `ebpf:"with_debug_output"`
}

// bpfUsdtObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfUsdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfUsdtObjects struct {
	bpfUsdtPrograms
	bpfUsdtMaps
	bpfUsdtVariables
}

func (o *bpfUsdtObjects) Close() error {
	return _BpfUsdtClose(
		&o.bpfUsdtPrograms,
		&o.bpfUsdtMaps,
	)
}

// bpfUsdtMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfUsdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfUsdtMaps struct {
	BpfUsdtSpecs    *ebpf.Map `ebpf:"__bpf_usdt_specs"`
	UsdtTestResults *ebpf.Map `ebpf:"usdt_test_results"`
}

func (m *bpfUsdtMaps) Close() error {
	return _BpfUsdtClose(
		m.BpfUsdtSpecs,
		m.UsdtTestResults,
	)
}

// bpfUsdtVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfUsdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfUsdtVariables struct {
	WithDebugOutput *ebpf.Variable `ebpf:"with_debug_output"`
}

// bpfUsdtPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfUsdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfUsdtPrograms struct {
	ConstProbe     *ebpf.Program `ebpf:"const_probe"`
	Int32Args      *ebpf.Program `ebpf:"int32_args"`
	Int64Args      *ebpf.Program `ebpf:"int64_args"`
	MemoryProbe    *ebpf.Program `ebpf:"memory_probe"`
	MixedProbe     *ebpf.Program `ebpf:"mixed_probe"`
	MixedRefs      *ebpf.Program `ebpf:"mixed_refs"`
	SimpleProbe    *ebpf.Program `ebpf:"simple_probe"`
	Uint8Args      *ebpf.Program `ebpf:"uint8_args"`
	UsdtDummyProbe *ebpf.Program `ebpf:"usdt_dummy_probe"`
	UsdtTestMulti  *ebpf.Program `ebpf:"usdt_test_multi"`
}

func (p *bpfUsdtPrograms) Close() error {
	return _BpfUsdtClose(
		p.ConstProbe,
		p.Int32Args,
		p.Int64Args,
		p.MemoryProbe,
		p.MixedProbe,
		p.MixedRefs,
		p.SimpleProbe,
		p.Uint8Args,
		p.UsdtDummyProbe,
		p.UsdtTestMulti,
	)
}

func _BpfUsdtClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfusdt_arm64_bpfel.o
var _BpfUsdtBytes []byte
