// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package testbpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type UsdtTestBpfUsdtSpec struct {
	_    structs.HostLayout
	Args [12]struct {
		_           structs.HostLayout
		ValOff      uint64
		ArgType     uint32
		RegId       uint8
		ArgSigned   bool
		ArgBitshift int8
		ArgIsFloat  bool
		Pad         [1]uint8
		_           [7]byte
	}
	UsdtCookie uint64
	ArgCnt     int16
	Pad        [6]uint8
}

// LoadUsdtTest returns the embedded CollectionSpec for UsdtTest.
func LoadUsdtTest() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UsdtTestBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load UsdtTest: %w", err)
	}

	return spec, err
}

// LoadUsdtTestObjects loads UsdtTest and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*UsdtTestObjects
//	*UsdtTestPrograms
//	*UsdtTestMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadUsdtTestObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadUsdtTest()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// UsdtTestSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsdtTestSpecs struct {
	UsdtTestProgramSpecs
	UsdtTestMapSpecs
	UsdtTestVariableSpecs
}

// UsdtTestProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsdtTestProgramSpecs struct {
	ConstProbe     *ebpf.ProgramSpec `ebpf:"const_probe"`
	Int32Args      *ebpf.ProgramSpec `ebpf:"int32_args"`
	Int64Args      *ebpf.ProgramSpec `ebpf:"int64_args"`
	MemoryProbe    *ebpf.ProgramSpec `ebpf:"memory_probe"`
	MixedProbe     *ebpf.ProgramSpec `ebpf:"mixed_probe"`
	MixedRefs      *ebpf.ProgramSpec `ebpf:"mixed_refs"`
	SimpleProbe    *ebpf.ProgramSpec `ebpf:"simple_probe"`
	Uint8Args      *ebpf.ProgramSpec `ebpf:"uint8_args"`
	UsdtDummyProbe *ebpf.ProgramSpec `ebpf:"usdt_dummy_probe"`
	UsdtTestMulti  *ebpf.ProgramSpec `ebpf:"usdt_test_multi"`
}

// UsdtTestMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsdtTestMapSpecs struct {
	BpfUsdtSpecs    *ebpf.MapSpec `ebpf:"__bpf_usdt_specs"`
	UsdtTestResults *ebpf.MapSpec `ebpf:"usdt_test_results"`
}

// UsdtTestVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsdtTestVariableSpecs struct {
	WithDebugOutput *ebpf.VariableSpec `ebpf:"with_debug_output"`
}

// UsdtTestObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadUsdtTestObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsdtTestObjects struct {
	UsdtTestPrograms
	UsdtTestMaps
	UsdtTestVariables
}

func (o *UsdtTestObjects) Close() error {
	return _UsdtTestClose(
		&o.UsdtTestPrograms,
		&o.UsdtTestMaps,
	)
}

// UsdtTestMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadUsdtTestObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsdtTestMaps struct {
	BpfUsdtSpecs    *ebpf.Map `ebpf:"__bpf_usdt_specs"`
	UsdtTestResults *ebpf.Map `ebpf:"usdt_test_results"`
}

func (m *UsdtTestMaps) Close() error {
	return _UsdtTestClose(
		m.BpfUsdtSpecs,
		m.UsdtTestResults,
	)
}

// UsdtTestVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadUsdtTestObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsdtTestVariables struct {
	WithDebugOutput *ebpf.Variable `ebpf:"with_debug_output"`
}

// UsdtTestPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadUsdtTestObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsdtTestPrograms struct {
	ConstProbe     *ebpf.Program `ebpf:"const_probe"`
	Int32Args      *ebpf.Program `ebpf:"int32_args"`
	Int64Args      *ebpf.Program `ebpf:"int64_args"`
	MemoryProbe    *ebpf.Program `ebpf:"memory_probe"`
	MixedProbe     *ebpf.Program `ebpf:"mixed_probe"`
	MixedRefs      *ebpf.Program `ebpf:"mixed_refs"`
	SimpleProbe    *ebpf.Program `ebpf:"simple_probe"`
	Uint8Args      *ebpf.Program `ebpf:"uint8_args"`
	UsdtDummyProbe *ebpf.Program `ebpf:"usdt_dummy_probe"`
	UsdtTestMulti  *ebpf.Program `ebpf:"usdt_test_multi"`
}

func (p *UsdtTestPrograms) Close() error {
	return _UsdtTestClose(
		p.ConstProbe,
		p.Int32Args,
		p.Int64Args,
		p.MemoryProbe,
		p.MixedProbe,
		p.MixedRefs,
		p.SimpleProbe,
		p.Uint8Args,
		p.UsdtDummyProbe,
		p.UsdtTestMulti,
	)
}

func _UsdtTestClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed usdttest_x86_bpfel.o
var _UsdtTestBytes []byte
